drop table if exists USERS cascade;
drop table if exists DB_LOCATIONS cascade;
drop table if exists COURSES cascade;
drop table if exists TESTS cascade;
drop table if exists QUESTIONS cascade;
drop table if exists ANSWERS cascade;
drop table if exists ATTEMPTS cascade;
drop table if exists ATTEMPTS_ANSWERS cascade;


drop sequence if exists USER_SEQUENCE ;
drop sequence if exists DB_LOCATION_SEQUENCE ;
drop sequence if exists COURSE_SEQUENCE ;
drop sequence if exists TEST_SEQUENCE ;
drop sequence if exists QUESTION_SEQUENCE ;
drop sequence if exists ANSWER_SEQUENCE ;
drop sequence if exists ATTEMPT_SEQUENCE ;


CREATE SEQUENCE IF NOT EXISTS USER_SEQUENCE START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS DB_LOCATION_SEQUENCE START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS COURSE_SEQUENCE START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS TEST_SEQUENCE START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS QUESTION_SEQUENCE START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS ANSWER_SEQUENCE START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS ATTEMPT_SEQUENCE START WITH 10 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS USERS
(
    ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(200) NOT NULL,
    LAST_NAME VARCHAR(200) NOT NULL,
    LOGIN VARCHAR(200) NOT NULL,
    PASSWORD VARCHAR(500) NOT NULL,
    ROLE VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS DB_LOCATIONS
(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(200),
    PATH VARCHAR(500),
    AUTHOR_ID INTEGER REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS COURSES
(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(200),
    DESCRIPTION VARCHAR(500),
    AUTHOR_ID INTEGER REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS TESTS
(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(200),
    MAX_ATTEMPTS_CNT INTEGER,
    DB_LOCATION_ID INTEGER REFERENCES DB_LOCATIONS(ID),
    COURSE_ID INTEGER REFERENCES COURSES(ID)
);

CREATE TABLE IF NOT EXISTS QUESTIONS
(
    ID SERIAL PRIMARY KEY,
    TEXT VARCHAR(500),
    TEST_ID INTEGER REFERENCES TESTS(ID)
);

CREATE TABLE IF NOT EXISTS ATTEMPTS
(
    ID SERIAL PRIMARY KEY,
    CREATED_AT TIMESTAMP,
    TEST_ID INTEGER REFERENCES TESTS(ID),
    AUTHOR_ID INTEGER REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS ANSWERS
(
    ID SERIAL PRIMARY KEY,
    TEXT VARCHAR(500),
    GRADE INTEGER,
    QUESTION_ID INTEGER REFERENCES QUESTIONS(ID),
    AUTHOR_ID INTEGER REFERENCES USERS(ID),
    ATTEMPT_ID INTEGER REFERENCES ATTEMPTS(ID)
);





